<?php 

//http status codes
return [

	"HTTP_CONTINUE" => 100,
	"HTTP_SWITCHING_PROTOCOLS" => 101,
	"HTTP_PROCESSING" => 102,
	"HTTP_OK" => 200,
	"HTTP_CREATED" => 201,
	"HTTP_ACCEPTED" => 202,
	"HTTP_NON_AUTHORITATIVE_INFORMATION" => 203,
	"HTTP_NO_CONTENT" => 204,
	"HTTP_RESET_CONTENT" => 205,
	"HTTP_PARTIAL_CONTENT" => 206,
	"HTTP_MULTI_STATUS" => 207,
	"HTTP_ALREADY_REPORTED" => 208,
	"HTTP_IM_USED" => 226,
	"HTTP_MULTIPLE_CHOICES" => 300,
	"HTTP_MOVED_PERMANENTLY" => 301,
	"HTTP_FOUND" => 302,
	"HTTP_SEE_OTHER" => 303,
	
	"HTTP_NOT_MODIFIED" => 304,
	"HTTP_USE_PROXY" => 305,
	"HTTP_RESERVED" => 306,
	"HTTP_TEMPORARY_REDIRECT" => 307,
	"HTTP_PERMANENTLY_REDIRECT" => 308,
	"HTTP_BAD_REQUEST" => 400,
	"HTTP_UNAUTHORIZED" => 401,
	"HTTP_PAYMENT_REQUIRED" => 402,
	"HTTP_FORBIDDEN" => 403,
	"HTTP_NOT_FOUND" => 404,
	"HTTP_METHOD_NOT_ALLOWED" => 405,
	"HTTP_NOT_ACCEPTABLE" => 406,
	"HTTP_PROXY_AUTHENTICATION_REQUIRED" => 407,

	"HTTP_REQUEST_TIMEOUT" => 408,
	"HTTP_CONFLICT" => 409,
	"HTTP_GONE" => 410,
	"HTTP_LENGTH_REQUIRED" => 411,
	"HTTP_PRECONDITION_FAILED" => 412,
	"HTTP_REQUEST_ENTITY_TOO_LARGE" => 413,

	"HTTP_REQUEST_URI_TOO_LONG" => 414,
	"HTTP_UNSUPPORTED_MEDIA_TYPE" => 415,
	"HTTP_REQUESTED_RANGE_NOT_SATISFIABLE" => 416,
	"HTTP_EXPECTATION_FAILED" => 417,
	"HTTP_I_AM_A_TEAPOT" => 418,
	"HTTP_UNPROCESSABLE_ENTITY" => 422,

	"HTTP_LOCKED" => 423,
	"HTTP_FAILED_DEPENDENCY" => 424,
	"HTTP_RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL" => 425,
	"HTTP_UPGRADE_REQUIRED" => 426,
	"HTTP_PRECONDITION_REQUIRED" => 428,
	"HTTP_TOO_MANY_REQUESTS" => 429,
	"HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE" => 431,

	"HTTP_INTERNAL_SERVER_ERROR" => 500,
	"HTTP_BAD_GATEWAY" => 502,
	"HTTP_SERVICE_UNAVAILABLE" => 503,
	"HTTP_GATEWAY_TIMEOUT" => 504,
	"HTTP_VERSION_NOT_SUPPORTED" => 505,
	"HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL" => 506,

	"HTTP_INSUFFICIENT_STORAGE" => 507,
	"HTTP_LOOP_DETECTED" => 508,
	"HTTP_NOT_EXTENDED" => 510,
	"HTTP_NETWORK_AUTHENTICATION_REQUIRED" => 511,
	"USER_NOT_EXIST" => 431,
	"USER_SESSION_ERROR" => 429,

	"DATA_NOT_FOUND" => 480,

	"USER_DOES_NOT_EXIST" => 501,
	"USER_LOGGED_IN_WITH_ANOTHER_DEVCIE" => 420,

	"USER_EMAIL_NOT_VERIFIED" => 551,
    "USER_PHONE_NOT_VERIFIED" => 552,
    "INVALID_OTP" => 571,
    "OTP_EXPIRED" => 572,

    "CARD_DATA_NOT_FOUND" => 600,
    "PAYMENT_NOT_PROCESSED" => 601,
    "PAGINATION_COUNT_LIMIT" => 10,
    
];

// defined ( "HTTP_CONTINUE" ) OR define ( "HTTP_CONTINUE", 100 );
// defined ( "HTTP_SWITCHING_PROTOCOLS" ) OR define ( "HTTP_SWITCHING_PROTOCOLS", 101 );
// defined ( "HTTP_PROCESSING" ) OR define ( "HTTP_PROCESSING", 102 );
// defined ( "HTTP_OK" ) OR define ( "HTTP_OK", 200 );
// defined ( "HTTP_CREATED" ) OR define ( "HTTP_CREATED", 201 );
// defined ( "HTTP_ACCEPTED" ) OR define ( "HTTP_ACCEPTED", 202 );
// defined ( "HTTP_NON_AUTHORITATIVE_INFORMATION" ) OR define ( "HTTP_NON_AUTHORITATIVE_INFORMATION", 203 );
// defined ( "HTTP_NO_CONTENT" ) OR define ( "HTTP_NO_CONTENT", 204 );
// defined ( "HTTP_RESET_CONTENT" ) OR define ( "HTTP_RESET_CONTENT", 205 );
// defined ( "HTTP_PARTIAL_CONTENT" ) OR define ( "HTTP_PARTIAL_CONTENT", 206 );
// defined ( "HTTP_MULTI_STATUS" ) OR define ( "HTTP_MULTI_STATUS", 207 );
// defined ( "HTTP_ALREADY_REPORTED" ) OR define ( "HTTP_ALREADY_REPORTED", 208 );
// defined ( "HTTP_IM_USED" ) OR define ( "HTTP_IM_USED", 226 );
// defined ( "HTTP_MULTIPLE_CHOICES" ) OR define ( "HTTP_MULTIPLE_CHOICES", 300 );
// defined ( "HTTP_MOVED_PERMANENTLY" ) OR define ( "HTTP_MOVED_PERMANENTLY", 301 );
// defined ( "HTTP_FOUND" ) OR define ( "HTTP_FOUND", 302 );
// defined ( "HTTP_SEE_OTHER" ) OR define ( "HTTP_SEE_OTHER", 303 );
// defined ( "HTTP_NOT_MODIFIED" ) OR define ( "HTTP_NOT_MODIFIED", 304 );
// defined ( "HTTP_USE_PROXY" ) OR define ( "HTTP_USE_PROXY", 305 );
// defined ( "HTTP_RESERVED" ) OR define ( "HTTP_RESERVED", 306 );
// defined ( "HTTP_TEMPORARY_REDIRECT" ) OR define ( "HTTP_TEMPORARY_REDIRECT", 307 );
// defined ( "HTTP_PERMANENTLY_REDIRECT" ) OR define ( "HTTP_PERMANENTLY_REDIRECT", 308 );
// defined ( "HTTP_BAD_REQUEST" ) OR define ( "HTTP_BAD_REQUEST", 400 );
// defined ( "HTTP_UNAUTHORIZED" ) OR define ( "HTTP_UNAUTHORIZED", 401 );
// defined ( "HTTP_PAYMENT_REQUIRED" ) OR define ( "HTTP_PAYMENT_REQUIRED", 402 );
// defined ( "HTTP_FORBIDDEN" ) OR define ( "HTTP_FORBIDDEN", 403 );
// defined ( "HTTP_NOT_FOUND" ) OR define ( "HTTP_NOT_FOUND", 404 );
// defined ( "HTTP_METHOD_NOT_ALLOWED" ) OR define ( "HTTP_METHOD_NOT_ALLOWED", 405 );
// defined ( "HTTP_NOT_ACCEPTABLE" ) OR define ( "HTTP_NOT_ACCEPTABLE", 406 );
// defined ( "HTTP_PROXY_AUTHENTICATION_REQUIRED" ) OR define ( "HTTP_PROXY_AUTHENTICATION_REQUIRED", 407 );

// defined ( "HTTP_REQUEST_TIMEOUT" ) OR define ( "HTTP_REQUEST_TIMEOUT", 408 );
// defined ( "HTTP_CONFLICT" ) OR define ( "HTTP_CONFLICT", 409 );
// defined ( "HTTP_GONE" ) OR define ( "HTTP_GONE", 410 );
// defined ( "HTTP_LENGTH_REQUIRED" ) OR define ( "HTTP_LENGTH_REQUIRED", 411 );
// defined ( "HTTP_PRECONDITION_FAILED" ) OR define ( "HTTP_PRECONDITION_FAILED", 412 );
// defined ( "HTTP_REQUEST_ENTITY_TOO_LARGE" ) OR define ( "HTTP_REQUEST_ENTITY_TOO_LARGE", 413 );
// defined ( "HTTP_REQUEST_URI_TOO_LONG" ) OR define ( "HTTP_REQUEST_URI_TOO_LONG", 414 );
// defined ( "HTTP_UNSUPPORTED_MEDIA_TYPE" ) OR define ( "HTTP_UNSUPPORTED_MEDIA_TYPE", 415 );
// defined ( "HTTP_REQUESTED_RANGE_NOT_SATISFIABLE" ) OR define ( "HTTP_REQUESTED_RANGE_NOT_SATISFIABLE", 416 );
// defined ( "HTTP_EXPECTATION_FAILED" ) OR define ( "HTTP_EXPECTATION_FAILED", 417 );
// defined ( "HTTP_I_AM_A_TEAPOT" ) OR define ( "HTTP_I_AM_A_TEAPOT", 418 );
// defined ( "HTTP_UNPROCESSABLE_ENTITY" ) OR define ( "HTTP_UNPROCESSABLE_ENTITY", 422 );
// defined ( "HTTP_LOCKED" ) OR define ( "HTTP_LOCKED", 423 );
// defined ( "HTTP_FAILED_DEPENDENCY" ) OR define ( "HTTP_FAILED_DEPENDENCY", 424 );
// defined ( "HTTP_RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL" ) OR define ( "HTTP_RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL", 425 );
// defined ( "HTTP_UPGRADE_REQUIRED" ) OR define ( "HTTP_UPGRADE_REQUIRED", 426 );
// defined ( "HTTP_PRECONDITION_REQUIRED" ) OR define ( "HTTP_PRECONDITION_REQUIRED", 428 );
// defined ( "HTTP_TOO_MANY_REQUESTS" ) OR define ( "HTTP_TOO_MANY_REQUESTS", 429 );
// defined ( "HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE" ) OR define ( "HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE", 431 );
// defined ( "HTTP_INTERNAL_SERVER_ERROR" ) OR define ( "HTTP_INTERNAL_SERVER_ERROR", 500 );
// defined ("HTTP_BAD_GATEWAY" ) OR define ( "HTTP_BAD_GATEWAY", 502 );
// defined ("HTTP_SERVICE_UNAVAILABLE" ) OR define ( "HTTP_SERVICE_UNAVAILABLE", 503 );
// defined ("HTTP_GATEWAY_TIMEOUT" ) OR define ( "HTTP_GATEWAY_TIMEOUT", 504 );
// defined ("HTTP_VERSION_NOT_SUPPORTED" ) OR define ( "HTTP_VERSION_NOT_SUPPORTED", 505 );
// defined ("HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL" ) OR define ( "HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL", 506 );
// defined ( "HTTP_INSUFFICIENT_STORAGE") OR define ( "HTTP_INSUFFICIENT_STORAGE", 507 );
// defined ( "HTTP_LOOP_DETECTED" ) OR define ( "HTTP_LOOP_DETECTED", 508 );
// defined ( "HTTP_NOT_EXTENDED" ) OR define ( "HTTP_NOT_EXTENDED", 510 );
// defined ( "HTTP_NETWORK_AUTHENTICATION_REQUIRED" ) OR define ( "HTTP_NETWORK_AUTHENTICATION_REQUIRED", 511 );
// defined ( "USER_NOT_EXIST" ) OR define ( "USER_NOT_EXIST", 431 );
// defined ( "USER_SESSION_ERROR" ) OR define ( "USER_SESSION_ERROR", 429 );
// defined ( "DATA_NOT_FOUND" ) OR define ( "DATA_NOT_FOUND", 480 );
// defined ( "USER_DOES_NOT_EXIST" ) OR define ( "USER_DOES_NOT_EXIST", 501 );
// defined ( "USER_LOGGED_IN_WITH_ANOTHER_DEVCIE" ) OR define ( "USER_LOGGED_IN_WITH_ANOTHER_DEVCIE", 420 );
//defined ( "USER_EMAIL_NOT_VERIFIED" ) OR define ( "USER_EMAIL_NOT_VERIFIED", 551 );
// defined ( "USER_PHONE_NOT_VERIFIED" ) OR define ( "USER_PHONE_NOT_VERIFIED", 552 );
// defined ( "INVALID_OTP" ) OR define ( "INVALID_OTP", 571 );
// defined ( "OTP_EXPIRED" ) OR define ( "OTP_EXPIRED", 572 );

//defined ( "CARD_DATA_NOT_FOUND" ) OR define ( "CARD_DATA_NOT_FOUND", 600 );
//defined ( "PAYMENT_NOT_PROCESSED" ) OR define ( "PAYMENT_NOT_PROCESSED", 601 );
?>